from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path


@dataclass(frozen=True)
class DeploymentOutputs:
    yaml_path: Path
    powershell_path: Path
    note_path: Path


def export_champion_profile(
    champion_path: Path,
    output_dir: Path,
    llama_server: str,
    lane: str,
    host: str = "127.0.0.1",
) -> DeploymentOutputs:
    champion = json.loads(champion_path.read_text(encoding="utf-8"))
    settings = champion["settings"]
    output_dir.mkdir(parents=True, exist_ok=True)
    yaml_path = output_dir / f"champion_{lane}.yaml"
    powershell_path = output_dir / f"champion_{lane}.ps1"
    note_path = output_dir / f"champion_{lane}_hermes.md"

    yaml_path.write_text(_yaml_profile(champion, lane), encoding="utf-8")
    powershell_path.write_text(_powershell_profile(champion, settings, llama_server, host), encoding="utf-8")
    note_path.write_text(_hermes_note(champion), encoding="utf-8")
    return DeploymentOutputs(yaml_path=yaml_path, powershell_path=powershell_path, note_path=note_path)


def _yaml_profile(champion: dict, lane: str) -> str:
    settings = champion["settings"]
    return "\n".join(
        [
            f"lane: {lane}",
            f"model: {champion['model_path']}",
            f"score: {champion['score']}",
            "settings:",
            f"  ctx: {settings.get('context_size', 0)}",
            f"  parallel: {settings.get('parallel', 1)}",
            f"  gpu_layers: {settings.get('gpu_layers', 99)}",
            f"  batch: {settings.get('batch_size', 2048)}",
            f"  ubatch: {settings.get('ubatch_size', 512)}",
            f"  flash_attention: {str(settings.get('flash_attention', True)).lower()}",
            "",
        ]
    )


def _powershell_profile(champion: dict, settings: dict, llama_server: str, host: str) -> str:
    ctx = int(settings.get("context_size") or 0)
    context_arg = f" --ctx-size {ctx}" if ctx else ""
    flash = "on" if settings.get("flash_attention", True) else "off"
    return (
        "# Generated by Agent Pilot Autobench.\n"
        f"& \"{llama_server}\" --model \"{champion['model_path']}\"{context_arg} "
        f"--parallel {settings.get('parallel', 1)} --gpu-layers {settings.get('gpu_layers', 99)} "
        f"--batch-size {settings.get('batch_size', 2048)} --ubatch-size {settings.get('ubatch_size', 512)} "
        f"--flash-attn {flash} --host {host} --port 8080 --metrics\n"
    )


def _hermes_note(champion: dict) -> str:
    return "\n".join(
        [
            "# Hermes Provider Note",
            "",
            f"Champion model: `{champion['model_name']}`",
            "",
            "Hermes provider URL:",
            "",
            "```text",
            "http://<your-machine-ip>:8080/v1/chat/completions",
            "```",
            "",
        ]
    )
